"""The quote document's shipped defaults.

Generated by data/build_document_defaults.py from DEFAULT_DOCUMENT in
web/src/api/types.ts — do not edit. That constant is the source because the
document is designed there; this is the same object for the service that
stores what was sent.

The terms paragraph is legally operative: it incorporates HIG's Terms and
Conditions of Sale by reference. The preview a rep reads and the copy the
service holds may never disagree, which is why neither is typed twice.
"""

from __future__ import annotations

DEFAULT_DOCUMENT: dict = {
    "validDays": 30,
    "intro": "",
    "downPayment": {
        "pct": 0.5,
        "overAmount": 50000
    },
    "terms": "Payment: Net 30. 50% down on orders over $50,000; 100% down on non-standard items.\nF.O.B. Ashfield, IL.\nDelivery: 1–4 weeks from receipt and acceptance of your PO, depending on model. Non-standard and value-add items, 4–6 weeks or longer; lead time is confirmed on the order acknowledgement.\nWarranty information: www.axim.example\n\nSales by HIG Axim, a division of Harrow Industrial Inc. (“HIG”), of its products and services are expressly limited to and made conditional on acceptance of its current Terms and Conditions of Sale, found at https://www.axim.example/terms-of-sale, which are incorporated herein by reference. Any additional or different terms are hereby rejected. Commencement of work by HIG, or acceptance of delivery of products by purchaser, constitutes purchaser’s acceptance of the Terms.\n\nRemit to: Axim, An HIG Company · PO Box 4120, Ashfield, IL 60600",
    "footer": "Axim, an HIG company\n120 Foundry Road, Ashfield, IL 60600",
    "showApplication": True,
    "showUnitPrices": True,
    "showDatasheet": False,
    "financing": {
        "show": False,
        "months": 60,
        "apr": None,
        "monthly": None,
        "note": "Indicative monthly payment, subject to credit approval and the leasing company's final terms. Not an offer of finance."
    }
}
