/**
 * Machines that exist and cannot be quoted yet.
 *
 * Generated by data/build_announced.py from data/announced-machines.json —
 * do not edit. That file records every figure's source and why the machine is
 * here rather than in the catalogue.
 *
 * A rep WILL be asked about a machine the manufacturer has announced, and the
 * honest answer is not silence. It is also not a quote: there is no Orbit part
 * number, so there is nothing to put on a line, and a made-up one would be worse
 * than the machine being absent. So it reads about and does not order.
 *
 * 0 series, 0 models.
 */
import type { ModelSpecs } from './specs';

export interface AnnouncedDoc {
  kind: 'datasheet' | 'brochure' | 'specification';
  name: string;
  url: string;
}

export interface AnnouncedSeries {
  name: string;
  /** The price book it will land in, once it lands. */
  technologyCode: string;
  announced: string;
  /** The manufacturer's or distributor's page. */
  page: string;
  /** Said plainly, on the screen. Not a bug and not a gap in the data. */
  whyNotQuotable: string;
  summary: string;
  documents: AnnouncedDoc[];
  models: string[];
}

export const ANNOUNCED: AnnouncedSeries[] = [
];

/** The figures, keyed by model, so specsFor answers for these too. */
export const ANNOUNCED_SPECS: Record<string, ModelSpecs> = {
};

/** What is coming to this price book, if anything. */
export function announcedFor(technologyCode?: string | null): AnnouncedSeries[] {
  if (!technologyCode) return [];
  return ANNOUNCED.filter((s) => s.technologyCode === technologyCode);
}
