/**
 * How a Corvus 7300-series part number is put together.
 *
 * Generated by data/build_cij7300.py from data/cij-7300-configurator.json —
 * do not edit. Every code and label there is transcribed from the supplied
 * guidance, and the generator refuses to run if a compatibility rule names a
 * code that does not exist.
 *
 * The positions are checked against the 947 real 6400-series part numbers in
 * the catalogue, which share the grammar: all 947 of them decode,
 * and 487 state a conduit length in words that agrees with
 * the code. That is the only part of this file the repository can verify — no
 * price page carries a 7300 — and it is the part a transcription gets wrong.
 */

export interface PartOption {
  code: string;
  label: string;
  /** Which printhead family, where the sheet groups them. */
  family?: string;
  /** An HP-resistant conduit, which the right-angled lengths rule out. */
  hpConduit?: boolean;
  /** position -> the codes there that this option needs. */
  requires?: Record<string, string[]>;
  /** position -> the codes there that this option cannot stand with. */
  excludes?: Record<string, string[]>;
  /** The sheet's own wording, shown rather than paraphrased. */
  why?: string;
}

export interface PartPosition {
  key: string;
  label: string;
  note?: string;
  options: PartOption[];
}

export interface PartConfigurator {
  code: string;
  name: string;
  technology: string;
  /** The worked example, reproduced from the sheet. */
  example: string;
  format: string;
  positions: PartPosition[];
}

export const CIJ_7300: PartConfigurator = {
  code: "CIJ7300",
  name: "Corvus 7300 Series",
  technology: "CIJ",
  example: "K414-W2-72-CVS",
  format: "K41{printer}-{printhead}{length}-{ink}-CVS",
  positions: [
    {
      key: "printer",
      label: "Printer",
      note: "The model selector fills P99x. The 7340 Prism takes 6, not 5.",
      options: [
        { code: "0", label: "7300 printer" },
        { code: "1", label: "7310 printer" },
        { code: "2", label: "7320 printer" },
        { code: "4", label: "7340 printer" },
        { code: "6", label: "7340 Prism printer" },
      ],
    },
    {
      key: "printhead",
      label: "Printhead",
      options: [
        { code: "U", label: "PH4 Standard (62 microns)", family: "midi" },
        { code: "X", label: "PH4 Standard (62 microns), HP-resistant conduit", family: "midi", hpConduit: true },
        { code: "H", label: "PH4 Standard (62 microns) for Prism printers", family: "midi", requires: {"printer": ["6"], "ink": ["74"]}, why: "For Prism printers, and 1316 ink only." },
        { code: "W", label: "PH4 Standard Plus (75 microns)", family: "midiPlus" },
        { code: "D", label: "PH4 Standard Plus (75 microns) for Prism printers", family: "midiPlus", requires: {"printer": ["6"]}, why: "For Prism printers." },
        { code: "1", label: "PH4 Compact (50 microns)", family: "mini" },
        { code: "2", label: "PH4 Compact (50 microns), HP-resistant conduit", family: "mini", hpConduit: true },
        { code: "3", label: "PH4 Compact (50 microns) for Prism printers", family: "mini", requires: {"printer": ["6"], "ink": ["74"]}, why: "For Prism printers, and 1316 ink only." },
      ],
    },
    {
      key: "length",
      label: "Conduit length and type",
      options: [
        { code: "0", label: "2 m straight" },
        { code: "1", label: "2 m right-angled", excludes: {"printhead": ["X", "2"]}, why: "Unavailable with HP-resistant conduits." },
        { code: "2", label: "4 m straight" },
        { code: "3", label: "4 m right-angled", excludes: {"printhead": ["X", "2"]}, why: "Unavailable with HP-resistant conduits." },
        { code: "6", label: "6 m straight", excludes: {"printer": ["6"], "printhead": ["1", "2", "3"]}, why: "Unavailable with the 7340 Prism or the PH4 Compact." },
        { code: "7", label: "6 m right-angled", excludes: {"printer": ["6"], "printhead": ["X", "2", "1", "3"]}, why: "Unavailable with HP-resistant conduit, the 7340 Prism or the PH4 Compact." },
      ],
    },
    {
      key: "ink",
      label: "Ink category",
      note: "A category, not one ink. The ink itself is chosen during commissioning — refer to the Ink Guide.",
      options: [
        { code: "27", label: "1121 UV-readable", requires: {"printhead": ["U", "X", "H", "1", "2", "3"]}, why: "For PH4 Standard or PH4 Compact. Uses an alternative pressure transducer." },
        { code: "17", label: "Other dye-based inks", requires: {"printhead": ["U", "X", "H", "W", "D", "1", "2", "3"]}, why: "Use with PH4 Standard; some also support PH4 Standard Plus or Compact. Choose the dye ink during commissioning." },
        { code: "72", label: "Soft-pigmented: 1009, 1033, 1079, 1088", requires: {"printhead": ["W"]}, why: "Requires PH4 Standard Plus. Choose the ink during commissioning." },
        { code: "67", label: "Hard-pigmented: 1043, 1053, 1059, 1069, 1306, 1311, 1320", requires: {"printer": ["6"], "printhead": ["D"]}, why: "Requires Prism plus PH4 Standard Plus for Prism. Choose during commissioning." },
        { code: "74", label: "1316 Brilliant White", requires: {"printer": ["6"], "printhead": ["H", "3"]}, why: "Requires a Prism printer and an PH4 Standard or Compact printhead." },
      ],
    },
  ],
};
