/**
 * The Corvus laser configurators, as data.
 *
 * A Corvus laser has no part number until it is configured — `L465E651BXABFUSAXX` is
 * thirteen decisions strung together — which is why the machine list for LSR was
 * empty. The price page's laser tabs are a form, not a list of orderable rows, so
 * there was nothing on them for the catalogue extractor to find.
 *
 * Every option, code and label here is out of
 * Price Page Extract/CLEAN Axim Laser System Configurator 2025 REV B, and each
 * configurator is checked against the worked example on its own tab before this file
 * is written. Options the workbook has withdrawn are left out.
 *
 * Generated by data/build_configurators.py. Do not hand-edit.
 */

export interface ConfiguratorOption {
  code: string;
  label: string;
  /** The heading the workbook files this option under, e.g. "30 & 60 Watt Options". */
  group?: string;
  /**
   * The codes in the depended-on position that permit this option.
   *
   * The workbook's headings are compatibility, not decoration: a 60 W tube does not
   * take a 10 W marking head, and an SHC100 head does not take an SHC60 lens. The
   * heading is prose, so it is resolved to codes by the generator rather than matched
   * again in the browser, and an option whose heading matches nothing is a build
   * error rather than an option nobody can pick.
   */
  requires?: string[];
}

export interface ConfiguratorPosition {
  label: string;
  /** A position the form does not ask about, e.g. the leading L for "a laser". */
  fixed?: string;
  /** The position whose answer decides which of these options are available. */
  dependsOn?: string;
  options: ConfiguratorOption[];
}

export interface Configurator {
  code: string;
  name: string;
  technology: string;
  /** '' for CSL, which concatenates; '-' for FSL, which does not. */
  joiner: string;
  /** The workbook's own worked example, which the generator reproduces exactly. */
  example: string;
  /** Position label -> the code the worked example uses. */
  defaults: Record<string, string>;
  positions: ConfiguratorPosition[];
  /** The workbook's numbered notes, by id. */
  warnings: Record<string, string>;
}

export const CONFIGURATORS: Configurator[] = [
  {
    "code": "CSL",
    "name": "Corvus CSL sealed-tube CO2 laser",
    "technology": "LSR",
    "joiner": "",
    "example": "L465E651BXABFUSAXX",
    "defaults": {
      "Product Type": "L",
      "Laser/System": "465",
      "Head (Marking Head)": "E",
      "Lens (mm)": "65",
      "Pilot Laser": "1",
      "I/O": "B",
      "Safety Module (Corvus)": "X",
      "Umbilical (Conduit)": "A",
      "BTU/BEU": "BF",
      "Country/Language": "US",
      "User Interface/Handheld": "A",
      "Sensing": "X",
      "Fume Extractor": "X"
    },
    "positions": [
      {
        "label": "Product Type",
        "fixed": "L",
        "options": []
      },
      {
        "label": "Laser/System",
        "options": [
          {
            "code": "411",
            "label": "10W, 10.6mm, IP54 Laser"
          },
          {
            "code": "412",
            "label": "10W, 10.6mm, IP65 Laser"
          },
          {
            "code": "413",
            "label": "10W, 9.3mm, IP54 Laser"
          },
          {
            "code": "414",
            "label": "10W, 9.3mm, IP65 Laser"
          },
          {
            "code": "431",
            "label": "30W, 10.6um, IP54 Laser"
          },
          {
            "code": "432",
            "label": "30W, 10.6um, IP65 Laser"
          },
          {
            "code": "433",
            "label": "30W, 9.3um, IP54 Laser"
          },
          {
            "code": "434",
            "label": "30W, 9.3um, IP65 Laser"
          },
          {
            "code": "435",
            "label": "30W, 10.2um, IP54 Laser"
          },
          {
            "code": "436",
            "label": "30W, 10.2um, IP65 Laser"
          },
          {
            "code": "461",
            "label": "60W, 10.6um, IP54 Laser"
          },
          {
            "code": "462",
            "label": "60W, 10.6um, IP65 Laser"
          },
          {
            "code": "463",
            "label": "60W, 9.3um, IP54 Laser"
          },
          {
            "code": "464",
            "label": "60W, 9.3um, IP65 Laser"
          },
          {
            "code": "465",
            "label": "60W, 10.2um, IP54 Laser"
          },
          {
            "code": "466",
            "label": "60W, 10.2um, IP65 Laser"
          }
        ]
      },
      {
        "label": "Head (Marking Head)",
        "options": [
          {
            "code": "C",
            "label": "(C) SHC60d, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "D",
            "label": "(D) SHC60d, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "N",
            "label": "(N) SHC100d, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "P",
            "label": "(P) SHC100d, Straight",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "E",
            "label": "(E) SHC60d, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "F",
            "label": "(F) SHC60d, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "Q",
            "label": "(Q) SHC100d, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "R",
            "label": "(R) SHC100d, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "G",
            "label": "(G) SHC150c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "H",
            "label": "(H) SHC150c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "K",
            "label": "(K) SHC-SF (Variable Focus), DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "L",
            "label": "(L) SHC-SF (Variable Focus), STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          }
        ],
        "dependsOn": "Laser/System"
      },
      {
        "label": "Lens (mm)",
        "options": [
          {
            "code": "61",
            "label": "(61) 64 mm",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "62",
            "label": "(62) 95 mm",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "63",
            "label": "(63) 127 mm",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "64",
            "label": "(64) 190 mm",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "65",
            "label": "(65) 254 mm",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "B1",
            "label": "(B1) 64 mm with positive air curtain fitting.",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "B2",
            "label": "(B2) 95 mm with positive air curtain fitting.",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "B3",
            "label": "(B3) 127 mm with positive air curtain fitting.",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "B4",
            "label": "(B4) 190 mm with positive air curtain fitting.",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "B5",
            "label": "(B5) 254 mm with positive air curtain fitting.",
            "group": "FOR SHC60",
            "requires": [
              "C",
              "D",
              "E",
              "F"
            ]
          },
          {
            "code": "11",
            "label": "(11) 100mm",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "12",
            "label": "(12) 150mm",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "13",
            "label": "(13) 200mm",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "14",
            "label": "(14) 300mm",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "15",
            "label": "(15) 351mm",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "16",
            "label": "(16) 400mm",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "17",
            "label": "(17) 63.5mm Variable",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "18",
            "label": "(18) 85mm Variable",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "A1",
            "label": "(A1) 100mm with positive air curtain fitting.",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "A2",
            "label": "(A2) 150mm with positive air curtain fitting.",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "A3",
            "label": "(A3) 200mm with positive air curtain fitting.",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "A4",
            "label": "(A4) 300mm with positive air curtain fitting.",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "A5",
            "label": "(A5) 351mm with positive air curtain fitting.",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "A6",
            "label": "(A6) 400mm with positive air curtain fitting.",
            "group": "FOR SHC100/120",
            "requires": [
              "N",
              "P",
              "Q",
              "R"
            ]
          },
          {
            "code": "51",
            "label": "(51) 100mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "52",
            "label": "(52) 150mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "53",
            "label": "(53) 200mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "54",
            "label": "(54) 300mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "55",
            "label": "(55) 351mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "56",
            "label": "(56) 400mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "57",
            "label": "(57) 500mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "58",
            "label": "(58) 600mm",
            "group": "FOR SHC150",
            "requires": [
              "G",
              "H"
            ]
          },
          {
            "code": "SF",
            "label": "(SF) Lens",
            "group": "FOR SHC-SF(Variable Focus)",
            "requires": [
              "K",
              "L"
            ]
          },
          {
            "code": "AF",
            "label": "(AF) Lens with air curtain",
            "group": "FOR SHC-SF(Variable Focus)",
            "requires": [
              "K",
              "L"
            ]
          }
        ],
        "dependsOn": "Head (Marking Head)"
      },
      {
        "label": "Pilot Laser",
        "options": [
          {
            "code": "X",
            "label": "No Pilot Laser"
          },
          {
            "code": "1",
            "label": "Pilot Laser"
          }
        ]
      },
      {
        "label": "I/O",
        "options": [
          {
            "code": "A",
            "label": "Hard-wired accessories connection"
          },
          {
            "code": "B",
            "label": "Quick connect panel with 6x plugs"
          },
          {
            "code": "C",
            "label": "Quick connect panel with 3x plugs"
          }
        ]
      },
      {
        "label": "Safety Module (Corvus)",
        "options": [
          {
            "code": "X",
            "label": "No Safety module"
          },
          {
            "code": "1",
            "label": "Safety module, machine integrated"
          }
        ]
      },
      {
        "label": "Umbilical (Conduit)",
        "options": [
          {
            "code": "A",
            "label": "(A) Umbilical, 3m",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "B",
            "label": "(B) Umbilical, 5m",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "C",
            "label": "(C) Umbilical, 10m",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "A",
            "label": "(A) Umbilical, 3m",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "B",
            "label": "(B) Umbilical, 5m",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "C",
            "label": "(C) Umbilical, 10m",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "D",
            "label": "(D) Umbilical, 3m right angled",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "E",
            "label": "(E) Umbilical, 5m  right angled",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "F",
            "label": "(F) Umbilical, 10m  right angled",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          }
        ],
        "dependsOn": "Laser/System"
      },
      {
        "label": "BTU/BEU",
        "options": [
          {
            "code": "XX",
            "label": "None"
          },
          {
            "code": "AD",
            "label": "(AD) BEU, 100mm, SHC60d, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AE",
            "label": "(AE) BTU, 200mm, SHC60d, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AF",
            "label": "(AF) BTU, 300mm, SHC60d, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AJ",
            "label": "(AJ) BEU, 100mm, SHC60d, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AK",
            "label": "(AK) BTU, 200mm, SHC60d, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AL",
            "label": "(AL) BTU, 300mm, SHC60d, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AA",
            "label": "(AA) BEU, 100mm, SHC100/120c, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AB",
            "label": "(AB) BTU, 200mm, SHC100/120c, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AC",
            "label": "(AC) BTU, 300mm, SHC100/120c, DOWN",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AG",
            "label": "(AG) BEU, 100mm, SHC100/120c, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AH",
            "label": "(AH) BTU, 200mm, SHC100/120c, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "AI",
            "label": "(AI) BTU, 300mm,SHC100/120c, STRAIGHT",
            "group": "10 Watt Options",
            "requires": [
              "411",
              "412",
              "413",
              "414"
            ]
          },
          {
            "code": "BD",
            "label": "(BD) BEU, 100mm, SHC60d, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BE",
            "label": "(BE) BTU, 200mm, SHC60d, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BF",
            "label": "(BF) BTU, 300mm, SHC60d, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BJ",
            "label": "(BJ) BEU, 100mm, SHC60d, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BK",
            "label": "(BK) BTU, 200mm, SHC60d, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BL",
            "label": "(BL) BTU, 300mm, SHC60d, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BA",
            "label": "(BA) BEU, 100mm, SHC100/120c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BB",
            "label": "(BB) BTU, 200mm, SHC100/120c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BC",
            "label": "(BC) BTU, 300mm, SHC100/120c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BG",
            "label": "(BG) BEU, 100mm, SHC100/120c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BH",
            "label": "(BH) BTU, 200mm, SHC100/120c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BI",
            "label": "(BI) BTU, 300mm, SHC100/120c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BM",
            "label": "(BM) BEU, 100mm, SHC150c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BN",
            "label": "(BN) BTU, 200mm, SHC150c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BO",
            "label": "(BO) BTU, 300mm, SHC150c, DOWN",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BP",
            "label": "(BP) BEU, 100mm, SHC150c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BQ",
            "label": "(BQ) BTU, 200mm, SHC150c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          },
          {
            "code": "BR",
            "label": "(BR) BTU, 300mm, SHC150c, STRAIGHT",
            "group": "30 & 60 Watt Options",
            "requires": [
              "431",
              "432",
              "433",
              "434",
              "435",
              "436",
              "461",
              "462",
              "463",
              "464",
              "465",
              "466"
            ]
          }
        ],
        "dependsOn": "Laser/System"
      },
      {
        "label": "Country/Language",
        "options": [
          {
            "code": "AE",
            "label": "United Arab Emirates"
          },
          {
            "code": "AR",
            "label": "Argentina"
          },
          {
            "code": "AU",
            "label": "Australia"
          },
          {
            "code": "BR",
            "label": "Brazil"
          },
          {
            "code": "BY",
            "label": "Belarus"
          },
          {
            "code": "CA",
            "label": "Canada"
          },
          {
            "code": "CL",
            "label": "Chile"
          },
          {
            "code": "CO",
            "label": "Colombia"
          },
          {
            "code": "CZ",
            "label": "Czech Republic"
          },
          {
            "code": "DE",
            "label": "Germany"
          },
          {
            "code": "DK",
            "label": "Denmark"
          },
          {
            "code": "EC",
            "label": "Ecuador"
          },
          {
            "code": "EG",
            "label": "Egypt"
          },
          {
            "code": "ES",
            "label": "Spain"
          },
          {
            "code": "FI",
            "label": "Finland"
          },
          {
            "code": "FR",
            "label": "France"
          },
          {
            "code": "GB",
            "label": "Great Britain"
          },
          {
            "code": "IT",
            "label": "Italy"
          },
          {
            "code": "JP",
            "label": "Japan"
          },
          {
            "code": "KE",
            "label": "Kenya"
          },
          {
            "code": "KR",
            "label": "Korea"
          },
          {
            "code": "MX",
            "label": "Mexico"
          },
          {
            "code": "NL",
            "label": "Netherlands"
          },
          {
            "code": "NO",
            "label": "Norway"
          },
          {
            "code": "NZ",
            "label": "New Zealand"
          },
          {
            "code": "PE",
            "label": "Peru"
          },
          {
            "code": "PL",
            "label": "Poland"
          },
          {
            "code": "PT",
            "label": "Portugal"
          },
          {
            "code": "RU",
            "label": "Russian"
          },
          {
            "code": "SA",
            "label": "Saudi Arabia"
          },
          {
            "code": "SE",
            "label": "Sweden"
          },
          {
            "code": "TW",
            "label": "Taiwan"
          },
          {
            "code": "TR",
            "label": "Turkey"
          },
          {
            "code": "TH",
            "label": "Thailand"
          },
          {
            "code": "UA",
            "label": "Ukraine"
          },
          {
            "code": "US",
            "label": "United States"
          },
          {
            "code": "VE",
            "label": "Venezula"
          },
          {
            "code": "VN",
            "label": "Vietnam"
          },
          {
            "code": "ZA",
            "label": "South Africa"
          },
          {
            "code": "ZS",
            "label": "VR China"
          },
          {
            "code": "ZZ",
            "label": "English language kit - no mains cable"
          }
        ]
      },
      {
        "label": "User Interface/Handheld",
        "options": [
          {
            "code": "X",
            "label": "(X) HDMI supply unit connector"
          },
          {
            "code": "Y",
            "label": "(Y) 8-pole supply unit connector"
          },
          {
            "code": "A",
            "label": "(A) CorvusVision Touch Screen + HDMI supply unit connector"
          },
          {
            "code": "B",
            "label": "(B) CorvusVision Touch Screen + HDMI supply unit connector + mounting"
          }
        ]
      },
      {
        "label": "Sensing",
        "options": [
          {
            "code": "X",
            "label": "No encoder or detector"
          }
        ]
      },
      {
        "label": "Fume Extractor",
        "options": [
          {
            "code": "X",
            "label": "No fume extractor"
          }
        ]
      }
    ],
    "warnings": {
      "1": "IP65 versions require filtered air supply units.",
      "2": "Marking head not compatible w/ BEU/BTU.",
      "3": "Marking Head not compatible with IP65 version."
    }
  },
  {
    "code": "FSL",
    "name": "Corvus FSL fibre laser",
    "technology": "LSR",
    "joiner": "-",
    "example": "FSL20-254-X-X-1-X-US",
    "defaults": {
      "Power": "FSL20",
      "Lens size": "254",
      "Beam Turning Unit": "X",
      "Safety Card": "X",
      "Touch screen PC": "1",
      "Mounting kit": "X",
      "Country kit": "US"
    },
    "positions": [
      {
        "label": "Power",
        "options": [
          {
            "code": "FSL20",
            "label": "20 Watts"
          },
          {
            "code": "FSL50",
            "label": "50 Watt"
          }
        ]
      },
      {
        "label": "Lens size",
        "options": [
          {
            "code": "100",
            "label": "100 mm"
          },
          {
            "code": "163",
            "label": "163 mm"
          },
          {
            "code": "254",
            "label": "254 mm"
          },
          {
            "code": "420",
            "label": "420 mm"
          }
        ]
      },
      {
        "label": "Beam Turning Unit",
        "options": [
          {
            "code": "1",
            "label": "Beam turning unit"
          },
          {
            "code": "X",
            "label": "Not required"
          }
        ]
      },
      {
        "label": "Safety Card",
        "options": [
          {
            "code": "1",
            "label": "Safety card additional dual interlock"
          },
          {
            "code": "X",
            "label": "Not required"
          }
        ]
      },
      {
        "label": "Touch screen PC",
        "options": [
          {
            "code": "1",
            "label": "Touch screen PC"
          },
          {
            "code": "X",
            "label": "Not required"
          }
        ]
      },
      {
        "label": "Mounting kit",
        "options": [
          {
            "code": "1",
            "label": "Cross mounting kit"
          },
          {
            "code": "2",
            "label": "Parallel mounting kit"
          },
          {
            "code": "X",
            "label": "Not required"
          }
        ]
      },
      {
        "label": "Country kit",
        "options": [
          {
            "code": "AR",
            "label": "Spanish language kit - free stripped mains cable"
          },
          {
            "code": "AU",
            "label": "English language kit - free stripped mains cable"
          },
          {
            "code": "BR",
            "label": "Brazilian language kit - free stripped mains cable"
          },
          {
            "code": "BY",
            "label": "Russian language kit - EU mains cable"
          },
          {
            "code": "US",
            "label": "English language kit - US mains cable"
          },
          {
            "code": "CL",
            "label": "Spanish language kit - free stripped mains cable"
          },
          {
            "code": "CO",
            "label": "Spanish language kit - US mains cable"
          },
          {
            "code": "CZ",
            "label": "Czech language kit - EU mains cable"
          },
          {
            "code": "DE",
            "label": "German language kit - EU mains cable"
          },
          {
            "code": "EC",
            "label": "Spanish language kit - US mains cable"
          },
          {
            "code": "ES",
            "label": "Spanish language kit - EU mains cable"
          },
          {
            "code": "FR",
            "label": "French language kit - EU mains cable"
          },
          {
            "code": "GB",
            "label": "English language kit - UK mains cable"
          },
          {
            "code": "IT",
            "label": "Italian language kit - EU mains cable"
          },
          {
            "code": "JP",
            "label": "Japan language kit - JP mains cable"
          },
          {
            "code": "KE",
            "label": "English language kit - UK mains cable"
          },
          {
            "code": "MX",
            "label": "Spanish language kit - US mains cable"
          },
          {
            "code": "NL",
            "label": "Dutch language kit - EU mains cable"
          },
          {
            "code": "NZ",
            "label": "English language kit - free stripped mains cable"
          },
          {
            "code": "PE",
            "label": "Spanish language kit - US mains cable"
          },
          {
            "code": "PL",
            "label": "Polish language kit - EU mains cable"
          },
          {
            "code": "PT",
            "label": "Portuguese language kit - EU mains cable"
          },
          {
            "code": "RU",
            "label": "Russian language kit - EU mains cable"
          },
          {
            "code": "US",
            "label": "English language kit - US mains cable"
          },
          {
            "code": "VE",
            "label": "Spanish language kit - US mains cable"
          },
          {
            "code": "ZA",
            "label": "English language kit - free stripped mains cable"
          },
          {
            "code": "ZS",
            "label": "Chinese (simplified) language kit - CH mains cable"
          },
          {
            "code": "ZZ",
            "label": "English language kit - no mains cable"
          }
        ]
      }
    ],
    "warnings": {}
  }
];

/** Compose a part number from one choice per position. */
export function composePartNumber(
  c: Configurator, chosen: Record<string, string>,
): string {
  return c.positions.map((p) => p.fixed ?? chosen[p.label] ?? '').join(c.joiner);
}
