/**
 * Items whose classification needs a person: 30.
 *
 * Two different problems, one worklist.
 *
 *   unclassified      0  nothing knows what this part is. None here,
 *                        because every price-page sheet implies a type — but in
 *                        production this is most of the list, since the question
 *                        is asked of the whole Orbit item master rather than of
 *                        a price-page extract.
 *   unearnedMachine  30  the product line says printer and nothing names
 *                        a model, so it resolved to 'part'. Promote it or leave
 *                        it; either answer removes the row.
 *
 * Price-page fallbacks are deliberately NOT here. 740 of them were, and a review
 * pointed out that agreeing with a correct one cannot shorten the list — only
 * changing it to something wrong can. They remain visible as classSource on every
 * item, which is where distrusting one belongs.
 *
 * Nothing is dropped to tidy this up. Orbit is the superset, and a tool that
 * silently omits a part somebody sells is worse than one that admits it does not
 * know. Setting a technology and a type here writes an override, which always
 * wins over both other sources.
 *
 * In production this is `cpq.v_classify_worklist`.
 *
 * Generated by data/build_classification.py. Do not hand-edit.
 */

export type ReviewReason = 'unclassified' | 'unearnedMachine';

export type GapRow = [
  itemNo: string, description: string,
  technology: string | null, role: string | null, why: ReviewReason,
  /** The product line it inherits from, where the hierarchy knows the part. */
  hierarchyLine: string | null,
];

export const NEEDS_REVIEW: GapRow[] = [
  ["1709529","Wrench,  5-Gallon Cap","VIJ","part","unearnedMachine","IV"],
  ["8653400","Handclean Hand Cleaner","PIJ","part","unearnedMachine","Hi Res"],
  ["8099525","Printhead Broach Kit","VIJ","part","unearnedMachine","IV"],
  ["6135630","Flush Bottle Assembly -IV","VIJ","part","unearnedMachine","IV"],
  ["9476684","Scanner, Hand Data Logic, RS232","PIJ","part","unearnedMachine","Hi Res"],
  ["3915580","Conditioner, TSO Non-Porous (Alcohol), 5 Gal","VIJ","part","unearnedMachine","IV"],
  ["9030456","Conditioner, TSO-6500 Non-Porous (Acetone), 5 Gal","VIJ","part","unearnedMachine","IV"],
  ["0378521","Conditioner, TWP (Water), 5 Gal","VIJ","part","unearnedMachine","IV"],
  ["9352874","Conditioner, TSO-4000 Non-Porous (MEK), 5 Gal","VIJ","part","unearnedMachine","IV"],
  ["9787754","Pressure Gauge","VIJ","part","unearnedMachine","IV"],
  ["8156464","Effluent Bottle Kit","VIJ","part","unearnedMachine","IV"],
  ["0877313KCS","Software, HR2600 Network Software","PIJ","part","unearnedMachine","Hi Res"],
  ["5840781","Software, HR2600 Network Software w/ 2 Hours Phone Setup Support & one time data base conversion support up to 6 hours","VIJ","part","unearnedMachine","IV"],
  ["6699424A-YW","Flushing System (Will flush up to 2 tasks worth of heads.  System includes all IDS's needed and enough tubing for 4 heads. Cap assys & additonal tubing kits purchased separately.)(Note: see Tech bulletin #T-05-07 \"When to recommend use of flushing system\")(Note: Add'l install fees apply.  See supplier spec sheet for part number & price.)","VIJ","part","unearnedMachine","IV"],
  ["2913754","Cap Assembly, 5 Gallon","VIJ","part","unearnedMachine","IV"],
  ["4193939","Cap Assembly, 30 Gallon","VIJ","part","unearnedMachine","IV"],
  ["6870691","I/O Board Kit (For Use with HR2600 Controllers)","PIJ","part","unearnedMachine","Hi Res"],
  ["1334426","I/O Alarm Tower, 3 color (Requires I/O Board 5760-392)","VIJ","part","unearnedMachine","IV"],
  ["7267652G24799","80/20 structural beam,  1.5\" X 3\" X 100\"","PIJ","part","unearnedMachine","Hi Res"],
  ["6225KQN-RF","Custom Font, Logo conversion, Mfg to Load on IJ Controller","PIJ","part","unearnedMachine","Hi Res"],
  ["5390177","VJ2600 Smart IDS with tubing kit, 2 task, Porous","VIJ","part","unearnedMachine","IV"],
  ["2144266","HR2600 Smart IDS, 2 task, Non Porous","VIJ","part","unearnedMachine","IV"],
  ["4974691","Accessory Hub, TJ","TIJ","part","unearnedMachine","Thermal Jet"],
  ["4198640","TJ Print Head Rollers Only, TJ500/1000","TIJ","part","unearnedMachine","Thermal Jet"],
  ["2665398v55","10\" Active Stroke E-Secondary Wipedown Stand-Alone System","PALM","part","unearnedMachine",null],
  ["0145413e51","20\" Active Stroke E-Secondary Wipedown Stand-Alone System","PALM","part","unearnedMachine",null],
  ["4700355t81","30\" Active Stroke E-Secondary Wipedown Stand-Alone System","PALM","part","unearnedMachine",null],
  ["3344100y2","5\" Active Stroke E-Secondary Wipedown Stand-Alone System","PALM","part","unearnedMachine",null],
  ["TYNR FL 3","WASA Heavy Duty Assy, 4\" Width - 6\", 8\", 10\" & 12\" Lengths ONLY","PALM","part","unearnedMachine",null],
  ["GJJD","Wipe (LA Only)","PALM","part","unearnedMachine",null]
];
