/**
 * What each model looks like, and where its page is.
 *
 * Generated by data/build_media.py from the captured portfolio. Do not
 * hand-edit — the mapping of model to page lives in that script, written out
 * by hand, because inferring it put the wrong photograph on a machine.
 *
 * 18 pages, 81 models, 28 KB of inlined thumbnails.
 *
 * `page` is a axim.example URL rather than a path into this repository, so
 * the link works from the preview, the artifact and the deployed app alike.
 */

import { MODEL_PHOTOS } from './photos';
import { VENDOR_MEDIA } from './vendorMedia';
import { VENDOR_DOCS } from './vendorDocs';

export interface ModelMedia {
  /**
   * 88px WebP data URI. Identification at a glance, not a product shot.
   *
   * Null where photo-map.json supplies a real photograph for every model on
   * this page: mediaFor would override it, so shipping it was two images in the
   * bundle and one on the screen.
   */
  thumb: string | null;
  /** The product page on axim.example. */
  page: string;
  /** The primary document's name, where the page offers one. */
  doc: string | null;
  /** Where that document lives. A PDF, unless docKind says otherwise. */
  docUrl: string | null;
  /**
   * What that document IS, so the link can be labelled honestly.
   *
   * REPORTED: a link reading 'datasheet (PDF)' that opened a product page.
   * Some models have only a brochure, and two vendors publish their
   * specification as a web page rather than a PDF; calling all three a
   * datasheet is how a rep ends up sending a customer the wrong thing.
   */
  docKind?: 'datasheet' | 'brochure' | 'specification' | null;
  /** The page's own specification table, deep-linked. */
  specUrl?: string | null;
  /** The brochure, where the page offers one AS WELL AS a datasheet. */
  brochure?: string | null;
  brochureUrl?: string | null;
  /** What Axim calls this on the page. */
  name: string;
  /**
   * 340px WebP, where a real photograph of the machine exists.
   *
   * For the one place a rep has committed to a machine and is looking at it.
   * Absent for a model whose only image is a captured page, because a capture
   * enlarged to 340px is a screenshot of a screenshot.
   */
  hero?: string;
}

const PAGES: Record<string, ModelMedia> = {
  "thorne-xl5000": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzBCMkU0RiIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+dGhvcm5lLXhsNTAwMDwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/productcoding/thermaltransfer-overprinting-axim/thornexl5000",
    doc: "Axim Thorne T800 Thermal Transfer Datasheet",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1767&PortalId=0",
    docKind: "datasheet",
    specUrl: "https://www.axim.example/products/productcoding/thermaltransfer-overprinting-axim/thornexl5000#lt-3410497-specifications",
    name: "Thorne T800",
  },
  "automated-label-applicator-systems": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzI0NUM4MCIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+YXV0b21hdGVkLWxhYmVsLWFwcGxpY2F0b3Itc3lzdGVtczwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/productcoding/labelapplicator",
    doc: null,
    docUrl: null,
    docKind: null,
    specUrl: null,
    name: "Automated Label Applicator Systems",
  },
  "high-resolution-industrial-inkjet-printing-for-case-coding": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzEyM0U2NiIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+bW9kZWwgMzwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/casecoding/highresolutioninkjet",
    doc: null,
    docUrl: null,
    docKind: null,
    specUrl: null,
    name: "HIGH RESOLUTION INDUSTRIAL INKJET PRINting for case coding",
  },
  "integrated-valve-ink-jet": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzBCMkU0RiIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+aW50ZWdyYXRlZC12YWx2ZS1pbmstamV0PC90ZXh0Pjwvc3ZnPg==",
    page: "https://www.axim.example/products/casecoding/largecharacterinkjet",
    doc: null,
    docUrl: null,
    docKind: null,
    specUrl: null,
    name: "Integrated Valve Ink Jet",
  },
  "iv18-dot-integrated-valve-print-head": {
    thumb: null,
    page: "https://www.axim.example/products/casecodinglabeling/largecharacterinkjetprinter/iv18-dot",
    doc: "Axim VJ2600 Brochure",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1699&PortalId=0",
    docKind: "brochure",
    specUrl: "https://www.axim.example/products/casecodinglabeling/largecharacterinkjetprinter/iv18-dot#lt-1650288-specifications",
    name: "IV18-Dot Integrated Valve Print Head",
  },
  "iv9-dot-integrated-valve-print-head": {
    thumb: null,
    page: "https://www.axim.example/products/casecodinglabeling/largecharacterinkjetprinter/iv9-dot",
    doc: "Axim VJ2600 Brochure",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1782&PortalId=0",
    docKind: "brochure",
    specUrl: "https://www.axim.example/products/casecodinglabeling/largecharacterinkjetprinter/iv9-dot#lt-1642280-specifications",
    name: "IV9-Dot Integrated Valve Print Head",
  },
  "la7000-automated-labeling-machine": {
    thumb: null,
    page: "https://www.axim.example/products/productcoding/labelapplicator/la7000",
    doc: "Axim LB5200 Technical Datasheet",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=3038&PortalId=0",
    docKind: "datasheet",
    specUrl: "https://www.axim.example/products/productcoding/labelapplicator/la7000#lt-3479396-specifications",
    brochure: "Axim LB5200 Brochure",
    brochureUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=2878&PortalId=0",
    name: "LB5200 Automated Labeling Machine",
  },
  "corvus-5400-continuous-ink-jet-coder": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzFCNEQ3MyIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+Y29ydnVzLTU0MDAtY29udGludW91cy1pbmstamV0LWNvZGVyPC90ZXh0Pjwvc3ZnPg==",
    page: "https://www.axim.example/products/productcoding/smallcharacter/corvus5400",
    doc: "Axim Corvus 5400 Prism Continuous Inkjet Datasheet",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1425&PortalId=0",
    docKind: "datasheet",
    specUrl: "https://www.axim.example/products/productcoding/smallcharacter/corvus5400#lt-1585240-specifications",
    name: "Corvus 5400 Continuous Ink Jet Coder",
  },
  "corvus-6400-continuous-inkjet-printer": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzBCMkU0RiIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+Y29ydnVzLTY0MDAtY29udGludW91cy1pbmtqZXQtcHJpbnRlcjwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/productcoding/smallcharactercontinuousinkjet(cij)printer/6400",
    doc: "Axim Corvus 6400 technical datasheet.pdf",
    docUrl: "https://www.axim.example/Portals/0/adam/Content/pC7OwFgRNkm_yOQy0Z1O9w/DownloadUrl/Axim%20Corvus%208900%20technical%20datasheet.pdf",
    docKind: "datasheet",
    specUrl: null,
    brochure: "Corvus 6400 CIJ Brochure.pdf",
    brochureUrl: "https://www.axim.example/Portals/0/adam/Content/b0-ZSwn9hEKbBG9RfmICgw/DownloadUrl/Corvus%208900%20CIJ%20Brochure.pdf",
    name: "Corvus 6400 Continuous Inkjet Printer",
  },
  "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzEyM0U2NiIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+bW9kZWwgNzwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/productcoding/smallcharacter/6400ps",
    doc: "Axim Corvus 6400 Plus Series Continuous Inkjet Datasheet",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1730&PortalId=0",
    docKind: "datasheet",
    specUrl: "https://www.axim.example/products/productcoding/smallcharacter/6400ps#lt-2125482-specifications",
    brochure: "6400-literature.pdf",
    brochureUrl: "https://www.axim.example/Portals/0/Downloads/6400-literature.pdf",
    name: "Corvus 6400 Plus Series CIJ Inkjet Printers - 6400, 6410, 6420, 6440",
  },
  "corvus-fsl20-fsl50-fiber-lasers": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzJENkI4RCIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+Y29ydnVzLWZzbDIwLWZzbDUwLWZpYmVyLWxhc2VyczwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/productcoding/lasercoders/corvusfsl20andfsl50fiberlasers",
    doc: "Axim LF30&50 Laser Coder Datasheet",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1683&PortalId=0",
    docKind: "datasheet",
    specUrl: "https://www.axim.example/products/productcoding/lasercoders/corvusfsl20andfsl50fiberlasers#lt-2060464-specifications",
    name: "Corvus FSL20 & FSL50 Fiber Lasers",
  },
  "corvus-laser-marking-machines-and-coders": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzFCNEQ3MyIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+Y29ydnVzLWxhc2VyLW1hcmtpbmctbWFjaGluZXMtYW5kLWNvZGVyczwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/productcoding/laser",
    doc: "Axim-Corvus-CSL60-Laser-Coder-Datasheet.pdf",
    docUrl: "https://www.axim.example/Portals/0/PDF/Axim-Corvus-CSL60-Laser-Coder-Datasheet.pdf",
    docKind: "datasheet",
    specUrl: null,
    name: "Corvus Laser Marking Machines and Coders",
  },
  "pa7100-print-and-apply-labeler": {
    thumb: null,
    page: "https://www.axim.example/products/palletlabeling/printapplylabeling/pa7100",
    doc: "Axim PL6300 Technical Datasheet.pdf",
    docUrl: "https://www.axim.example/Portals/0/adam/Content/kz0RfVyTLUGlFiswfxHTlw/DownloadUrl/Axim%20PL6300%20Technical%20Datasheet.pdf",
    docKind: "datasheet",
    specUrl: null,
    brochure: "Axim PL6300 Brochure-1.pdf",
    brochureUrl: "https://www.axim.example/Portals/0/adam/Content/P_J3VhiSQk-xsdii4m0NFA/DownloadUrl/Axim%20PL6300%20Brochure-1.pdf",
    name: "PL6300 Print and Apply Labeler",
  },
  "ridgeline-5000-case-coding-printer": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzJENkI4RCIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+cmlkZ2VsaW5lLTUwMDAtY2FzZS1jb2RpbmctcHJpbnRlcjwvdGV4dD48L3N2Zz4=",
    page: "https://www.axim.example/products/casecodinglabeling/ridgeline5000highresolutioninkjetprinter/ridgeline5000",
    doc: "Ridgeline 3200 Technical Datasheet-1.pdf",
    docUrl: "https://www.axim.example/Portals/0/adam/Content/zCAv1fNCWEqGxnl1RvOluA/DownloadUrl/Ridgeline%205000%20Technical%20Datasheet-1.pdf",
    docKind: "datasheet",
    specUrl: null,
    brochure: "Axim Ridgeline 3200 Brochure.pdf",
    brochureUrl: "https://www.axim.example/Portals/0/adam/Content/KPSJTjHW8kG0WXLpIk29BA/DownloadUrl/Axim%20Ridgeline%205000%20Brochure.pdf",
    name: "Ridgeline 3200 Case Coding Printer",
  },
  "small-character-continuous-inkjet-printers": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzI0NUM4MCIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+bW9kZWwgMTE8L3RleHQ+PC9zdmc+",
    page: "https://www.axim.example/products/productcoding/small-character",
    doc: null,
    docUrl: null,
    docKind: null,
    specUrl: null,
    name: "Small Character Continuous InkJet Printers",
  },
  "thermal-transfer-overprinters-tto": {
    thumb: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iIzI0NUM4MCIvPjxyZWN0IHg9IjQzIiB5PSIzMSIgd2lkdGg9IjczIiBoZWlnaHQ9IjUwIiByeD0iNSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utb3BhY2l0eT0iLjU1IiBzdHJva2Utd2lkdGg9IjIiLz48cmVjdCB4PSI1NSIgeT0iNDEiIHdpZHRoPSI0OCIgaGVpZ2h0PSIxMiIgcng9IjIiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjI4Ii8+PHJlY3QgeD0iMjUiIHk9IjkxIiB3aWR0aD0iMTA4IiBoZWlnaHQ9IjMiIGZpbGw9IiNGRkZGRkYiIGZpbGwtb3BhY2l0eT0iLjM1Ii8+PHRleHQgeD0iNTAlIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJTZWdvZSBVSSxzeXN0ZW0tdWksc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1vcGFjaXR5PSIuOCI+dGhlcm1hbC10cmFuc2Zlci1vdmVycHJpbnRlcnMtdHRvPC90ZXh0Pjwvc3ZnPg==",
    page: "https://www.axim.example/products/productcoding/thermaltransfer",
    doc: null,
    docUrl: null,
    docKind: null,
    specUrl: null,
    name: "Thermal Transfer Overprinters (TTO)",
  },
  "tj1000-thermal-jet-printhead": {
    thumb: null,
    page: "https://www.axim.example/products/productcoding/thermalindustrialinkjetprinter/tj-1000",
    doc: "Axim HP Thermal Jet System Brochure",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1440&PortalId=0",
    docKind: "brochure",
    specUrl: "https://www.axim.example/products/productcoding/thermalindustrialinkjetprinter/tj-1000#lt-1603248-specifications",
    name: "TJ1000 Thermal Jet Printhead",
  },
  "tj500-thermal-jet-printhead": {
    thumb: null,
    page: "https://www.axim.example/products/productcoding/thermalinkjet/tj-500",
    doc: "Axim HP Thermal Jet System Brochure",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1437&PortalId=0",
    docKind: "brochure",
    specUrl: "https://www.axim.example/products/productcoding/thermalinkjet/tj-500#lt-1598244-specifications",
    name: "TJ500 Thermal Jet Printhead",
  },
};

const MODEL_PAGE: Record<string, string> = {
  "256D": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384-IJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384-PRO": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384E": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384E-IJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384E-PRO": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384e": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384e-IJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "384e-PRO": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "3400": "small-character-continuous-inkjet-printers",
  "3400 Ethernet": "small-character-continuous-inkjet-printers",
  "768": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768-IJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768-PRO": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768E": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768E-IJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768E-PRO": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768e": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "768e-IJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "5400": "corvus-5400-continuous-ink-jet-coder",
  "5400 IP65": "corvus-5400-continuous-ink-jet-coder",
  "5400 Prism": "corvus-5400-continuous-ink-jet-coder",
  "6400": "corvus-6400-continuous-inkjet-printer",
  "6400LI": "corvus-6400-continuous-inkjet-printer",
  "6400PLUS": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "6410": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "6410PLUS": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "6420": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "6420PLUS": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "6440": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "6440PLUS": "corvus-6400-plus-series-cij-inkjet-printers-6400-6410-6420-6440",
  "Alphacoder": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "CJ250": "small-character-continuous-inkjet-printers",
  "CJ250LE": "small-character-continuous-inkjet-printers",
  "CSL10": "corvus-laser-marking-machines-and-coders",
  "CSL10 IP65": "corvus-laser-marking-machines-and-coders",
  "CSL30": "corvus-laser-marking-machines-and-coders",
  "CSL30 IP65": "corvus-laser-marking-machines-and-coders",
  "CSL60": "corvus-laser-marking-machines-and-coders",
  "CSL60 IP65": "corvus-laser-marking-machines-and-coders",
  "HP 0.5\"": "tj500-thermal-jet-printhead",
  "HP 1.0\"": "tj1000-thermal-jet-printhead",
  "IV12": "integrated-valve-ink-jet",
  "IV18": "iv18-dot-integrated-valve-print-head",
  "IV7": "integrated-valve-ink-jet",
  "IV9": "iv9-dot-integrated-valve-print-head",
  "LA4700/LS4700": "automated-label-applicator-systems",
  "LB3100/LS4750": "automated-label-applicator-systems",
  "LB5200/LS7000": "la7000-automated-labeling-machine",
  "LT Series": "thermal-transfer-overprinters-tto",
  "Corvus 4900": "small-character-continuous-inkjet-printers",
  "Corvus 6800": "small-character-continuous-inkjet-printers",
  "Corvus 6900": "small-character-continuous-inkjet-printers",
  "Corvus 7300": "small-character-continuous-inkjet-printers",
  "PH4": "corvus-6400-continuous-inkjet-printer",
  "MK5": "corvus-6400-continuous-inkjet-printer",
  "MK7": "corvus-6400-continuous-inkjet-printer",
  "MK9": "corvus-6400-continuous-inkjet-printer",
  "T200": "thermal-transfer-overprinters-tto",
  "Mark 2": "ridgeline-5000-case-coding-printer",
  "Mark 4": "ridgeline-5000-case-coding-printer",
  "T400 Series": "thermal-transfer-overprinters-tto",
  "NX Series": "thermal-transfer-overprinters-tto",
  "PA4600/LS4600": "automated-label-applicator-systems",
  "PL4500/LS6000": "automated-label-applicator-systems",
  "PL6300/LS7100": "pa7100-print-and-apply-labeler",
  "Ridgeline 3200": "ridgeline-5000-case-coding-printer",
  "SL1": "corvus-fsl20-fsl50-fiber-lasers",
  "SL101": "corvus-fsl20-fsl50-fiber-lasers",
  "SL102": "corvus-fsl20-fsl50-fiber-lasers",
  "SL301": "corvus-fsl20-fsl50-fiber-lasers",
  "SL302": "corvus-fsl20-fsl50-fiber-lasers",
  "SL501": "corvus-fsl20-fsl50-fiber-lasers",
  "SST Series": "thermal-transfer-overprinters-tto",
  "SolidJet": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "TP Series": "thermal-transfer-overprinters-tto",
  "TP4100": "thermal-transfer-overprinters-tto",
  "UJ": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "UJ II": "high-resolution-industrial-inkjet-printing-for-case-coding",
  "XL Series": "thorne-xl5000",
};

/**
 * Media for a model, or null.
 *
 * Null is a normal answer and not a gap to paper over: most parts in the
 * catalogue are consumables and spares with no model at all, and a model
 * whose page was never captured has nothing honest to show.
 */
export function mediaFor(model: string | null | undefined): ModelMedia | null {
  if (!model) return null;
  /* Machines somebody else publishes.
     A PE311 is a Palisade engine and an K84X is a Kestrel one; both go inside a Axim
     applicator, so neither will ever appear in a capture of axim.example. Sixteen
     quotable parts carried a model, a role of 'printer' and no picture at all.
     Checked first, because for these models there is nothing behind it to fall
     back to. */
  const vendor = VENDOR_MEDIA[model];
  if (vendor) return vendor;
  const slug = MODEL_PAGE[model];
  /* A model-specific document, where the page's own is about the whole range.
     The four Plus-series machines share one page and one combined datasheet; Corvus
     publishes a sheet per machine, and a rep quoting an 6440 wants that one. See
     data/vendor-docs.json. */
  const extra = VENDOR_DOCS[model];
  const page = slug
    ? (extra ? { ...PAGES[slug], ...extra } : PAGES[slug])
    : null;
  /* A real photograph beats a website capture, so where photo-map.json supplies
     one it wins the image. The page link and the datasheet still come from the
     captured portfolio, because a photograph carries neither. */
  const photo = MODEL_PHOTOS[model];
  if (!photo) return page;
  return page
    ? { ...page, thumb: photo.thumb, hero: photo.hero }
    : { thumb: photo.thumb, hero: photo.hero, page: '', doc: null,
        docUrl: null, docKind: null, specUrl: null, name: model };
}
