/**
 * Product Line -> technology and type. The whole taxonomy, 43 rows.
 *
 * Two levels is all the classification needs: which price book a part belongs
 * to, and what kind of thing it is. The model (Product Type: 6420, 5400 IP65,
 * PH4) rides along on the item rather than being a third level, because it is
 * an attribute of the part and not a branch of the tree.
 *
 * 13 rows are marked 'assumed' — my reading of a line name rather than a
 * decision anybody made. Those are the ones to check before trusting the machine
 * list, and the admin screen sorts them first.
 *
 * Editable source: data/product-line-map.json.
 * Generated by data/build_classification.py. Do not hand-edit.
 */

export interface LineRow {
  line: string;
  class: string;
  technology: string | null;
  role: string;
  quotable: boolean;
  confidence: string;
  note?: string;
}

export const LINE_MAP: { lines: LineRow[] } = {
  lines: [
  { line: "Corvus 6400", class: "CIJ", technology: "CIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Corvus 5400", class: "CIJ", technology: "CIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Corvus 3400", class: "CIJ", technology: "CIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Corvus Legacy", class: "CIJ", technology: "CIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "CIJ Print Heads", class: "CIJ", technology: "CIJ", role: "printhead", quotable: true, confidence: "confirmed" },
  { line: "CIJ Consumables", class: "CIJ", technology: "CIJ", role: "consumable", quotable: true, confidence: "confirmed" },
  { line: "CIJ Accessories", class: "CIJ", technology: "CIJ", role: "accessory", quotable: true, confidence: "confirmed" },
  { line: "CIJ Service Parts", class: "CIJ", technology: "CIJ", role: "spare", quotable: true, confidence: "confirmed" },
  { line: "CIJ Promo Discounts", class: "CIJ", technology: "CIJ", role: "promo", quotable: true, confidence: "confirmed" },
  { line: "TTO Printers", class: "TTO", technology: "TTO", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "TTO Consumables", class: "TTO", technology: "TTO", role: "consumable", quotable: true, confidence: "confirmed" },
  { line: "TTO Accessories", class: "TTO", technology: "TTO", role: "accessory", quotable: true, confidence: "confirmed" },
  { line: "TTO Parts", class: "TTO", technology: "TTO", role: "spare", quotable: true, confidence: "confirmed" },
  { line: "TTO Service", class: "TTO", technology: "TTO", role: "service", quotable: true, confidence: "confirmed" },
  { line: "Print and Apply", class: "ALP", technology: "PALM", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Label Applicator", class: "ALP", technology: "PALM", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Print Engines", class: "ALP", technology: "PALM", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "ALP Consumables", class: "ALP", technology: "PALM", role: "consumable", quotable: true, confidence: "confirmed" },
  { line: "ALP Accessories", class: "ALP", technology: "PALM", role: "accessory", quotable: true, confidence: "confirmed" },
  { line: "ALP Parts", class: "ALP", technology: "PALM", role: "spare", quotable: true, confidence: "confirmed" },
  { line: "ALP Service", class: "ALP", technology: "PALM", role: "service", quotable: true, confidence: "confirmed" },
  { line: "Apply Modules", class: "ALP", technology: "PALM", role: "accessory", quotable: true, confidence: "assumed", note: "A configurable module of a print-and-apply system rather than a standalone machine, so it is not offered as a machine to grade. Change role to printer if you want these to appear in the machine list." },
  { line: "ALP Options", class: "ALP", technology: "PALM", role: "accessory", quotable: true, confidence: "assumed" },
  { line: "Material Handling", class: "ALP", technology: "PALM", role: "accessory", quotable: true, confidence: "assumed", note: "Conveyors and stands. 1,260 rows under ALP and 3 under TTO; the 3 TTO rows follow the same rule." },
  { line: "System Web", class: "ALP", technology: "PALM", role: "printer", quotable: true, confidence: "assumed" },
  { line: "System Hand", class: "ALP", technology: "PALM", role: "printer", quotable: true, confidence: "assumed" },
  { line: "System Orientation", class: "ALP", technology: "PALM", role: "accessory", quotable: true, confidence: "assumed" },
  { line: "Hi Res", class: "Coding", technology: "PIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "IV", class: "Coding", technology: "VIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Thermal Jet", class: "Coding", technology: "TIJ", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "Engines", class: "Coding", technology: "PIJ", role: "printhead", quotable: true, confidence: "assumed", note: "342 rows. Read as the printhead engines behind Hi Res. If Engines spans more than one price book this row has to split by Product Type." },
  { line: "Service", class: "Coding", technology: null, role: "service", quotable: false, confidence: "assumed", note: "8 rows, no technology in the name. Not offered until it is known which book they belong to." },
  { line: "DNR", class: "Coding", technology: null, role: "spare", quotable: false, confidence: "assumed", note: "Read as do-not-reorder. Never quotable." },
  { line: "COD", class: "Coding", technology: null, role: "service", quotable: false, confidence: "assumed" },
  { line: "CSL LASER", class: "LASER", technology: "LSR", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "SL LASER", class: "LASER", technology: "LSR", role: "printer", quotable: true, confidence: "confirmed" },
  { line: "LASER ACCESSORIES", class: "LASER", technology: "LSR", role: "accessory", quotable: true, confidence: "confirmed" },
  { line: "LASER TUBE", class: "LASER", technology: "LSR", role: "spare", quotable: true, confidence: "confirmed" },
  { line: "LASER SERVICE", class: "LASER", technology: "LSR", role: "service", quotable: true, confidence: "confirmed" },
  { line: "LASER PROMO SKU", class: "LASER", technology: "LSR", role: "promo", quotable: true, confidence: "confirmed" },
  { line: "Scanners", class: "Vision Systems", technology: null, role: "accessory", quotable: false, confidence: "assumed", note: "Vision Systems has no price book yet. 3 rows." },
  { line: "Axim NEXT", class: "IIoT and Management", technology: null, role: "service", quotable: false, confidence: "assumed", note: "Software and IIoT. No price book yet. 2 rows." },
  { line: "Lease Billing", class: "Lease Billing", technology: null, role: "service", quotable: false, confidence: "assumed", note: "Finance, not product. 1 row." }
  ],
};

/** Parts per Product Line in Global_Product_Hierarchy — so the screen can show weight. */
export const LINE_COUNTS: Record<string, number> = {
  "ALP Accessories": 684,
  "ALP Consumables": 144,
  "ALP Options": 42,
  "ALP Parts": 3721,
  "ALP Service": 89,
  "Apply Modules": 165,
  "CIJ Accessories": 471,
  "CIJ Consumables": 311,
  "CIJ Print Heads": 77,
  "CIJ Promo Discounts": 40,
  "CIJ Service Parts": 714,
  "COD": 1,
  "CSL LASER": 86,
  "DNR": 5,
  "Axim NEXT": 2,
  "Engines": 342,
  "Hi Res": 1565,
  "IV": 512,
  "LASER ACCESSORIES": 202,
  "LASER PROMO SKU": 2,
  "LASER SERVICE": 3,
  "LASER TUBE": 3,
  "Label Applicator": 69,
  "Lease Billing": 1,
  "Corvus 3400": 1117,
  "Corvus 5400": 944,
  "Corvus 6400": 468,
  "Corvus Legacy": 207,
  "Material Handling": 1263,
  "Print Engines": 279,
  "Print and Apply": 69,
  "SL LASER": 58,
  "Scanners": 3,
  "Service": 8,
  "System Hand": 6,
  "System Orientation": 5,
  "System Web": 12,
  "TTO Accessories": 532,
  "TTO Consumables": 417,
  "TTO Parts": 3754,
  "TTO Printers": 113,
  "TTO Service": 64,
  "Thermal Jet": 252
};

/**
 * Which item attributes name the MACHINE, per technology.
 *
 * A CIJ part number is a printer already filled — printer, printhead, ink and
 * colour in one SKU — so listing every one of them answers "which machine" with
 * 947 rows. The keys here are the ones that say which machine it is; everything
 * else is how that machine is filled, and belongs to the choice made after one
 * is picked. A technology with no entry is not grouped.
 *
 * Editable source: data/product-type-map.json.
 */
export const MACHINE_IDENTITY: Record<string, string[]> = {
  "CIJ": [
    "Printer Type"
  ]
};
