/**
 * Datasheet links and vendor specifications the captured portfolio does not carry.
 *
 * Generated by data/build_vendor_docs.py from data/vendor-docs.json — do not edit.
 * That file records where every figure was transcribed from, why none is carried
 * across between models, and why each link is here rather than on the page.
 *
 * 9 link overrides, 19 transcribed specification tables.
 */

/** A link override. `docKind` labels the link; see ModelMedia. */
export const VENDOR_DOCS: Record<string, {
  doc: string;
  docUrl: string;
  docKind: 'datasheet' | 'brochure' | 'specification';
}> = {
  "6440": {
    doc: "Corvus 6440 datasheet",
    docUrl: "https://www.corvus.example/wp-content/uploads/2023/06/corvus-6440-datasheet-mp42172_05.pdf",
    docKind: "datasheet",
  },
  "6420": {
    doc: "Corvus 6420 datasheet",
    docUrl: "https://www.corvus.example/wp-content/uploads/2023/06/corvus-6420-datasheet.pdf",
    docKind: "datasheet",
  },
  "6410": {
    doc: "Corvus 6400/6410 datasheet",
    docUrl: "https://www.corvus.example/wp-content/uploads/2023/06/corvus-6400-6410-datasheet.pdf",
    docKind: "datasheet",
  },
  "T400 Series": {
    doc: "Thorne T400 Series Thermal Transfer Datasheet",
    docUrl: "https://www.axim.example/DesktopModules/Bring2mind/DMX/Download.aspx?EntryId=1478&PortalId=0",
    docKind: "datasheet",
  },
  "7300": {
    doc: "Corvus 7300 Series brochure (MP41306/2)",
    docUrl: "https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
    docKind: "brochure",
  },
  "7310": {
    doc: "Corvus 7300 Series brochure (MP41306/2)",
    docUrl: "https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
    docKind: "brochure",
  },
  "7320": {
    doc: "Corvus 7300 Series brochure (MP41306/2)",
    docUrl: "https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
    docKind: "brochure",
  },
  "7340": {
    doc: "Corvus 7300 Series brochure (MP41306/2)",
    docUrl: "https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
    docKind: "brochure",
  },
  "7340 Prism": {
    doc: "Corvus 7300 Series brochure (MP41306/2)",
    docUrl: "https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
    docKind: "brochure",
  },
};

/** Figures transcribed from a vendor's own document, with that document named. */
export const VENDOR_SPECS: Record<string, { page: string; specs: Record<string, string> }> =
  {
    "PE311": {
      "page": "PE311/PE321 Print Engines Specification Sheet — https://www.palisade.example/content/dam/palisade_dam/en/spec-sheets/ze511-ze521-spec-sheet-en-us.pdf",
      "specs": {
        "Print width": "4.09 in / 104 mm",
        "Resolution": "203 dpi; 300 dpi and 600 dpi optional",
        "Maximum print speed": "18 ips at 203 dpi; 14 ips at 300 dpi; 6 ips at 600 dpi",
        "Media width": "0.625 to 4.5 in",
        "Connectivity": "USB 2.0, RS-232 serial, 10/100 Ethernet, Bluetooth 4.1, dual USB host",
        "Operating temperature": "31°F to 104°F / 0°C to 40°C",
        "Construction": "All-metal, no cooling fans"
      }
    },
    "PE321": {
      "page": "PE311/PE321 Print Engines Specification Sheet — https://www.palisade.example/content/dam/palisade_dam/en/spec-sheets/ze511-ze521-spec-sheet-en-us.pdf",
      "specs": {
        "Print width": "6.6 in / 168 mm",
        "Resolution": "203 dpi; 300 dpi optional",
        "Maximum print speed": "14 ips at 203 dpi; 12 ips at 300 dpi",
        "Media width": "3 to 7.1 in",
        "Connectivity": "USB 2.0, RS-232 serial, 10/100 Ethernet, Bluetooth 4.1, dual USB host",
        "Operating temperature": "31°F to 104°F / 0°C to 40°C",
        "Construction": "All-metal, no cooling fans"
      }
    },
    "6410": {
      "page": "Corvus 6400/6410 datasheet MP41215/12 — https://www.corvus.example/wp-content/uploads/2023/06/corvus-6400-6410-datasheet.pdf",
      "specs": {
        "Printhead": "Mk11 Standard (62 µm nozzle) or Mk11 Standard plus (75 µm)",
        "Lines of print": "1, 2 or 3",
        "Character height": "1.8 to 20 mm (Standard); 2.1 to 20 mm (Standard plus)",
        "Max speed, single line": "6.25 m/s / 1,230 fpm (Standard); 7.28 m/s / 1,433 fpm (Standard plus)",
        "Max speed, two line": "2.09 m/s / 411 fpm (Standard); 2.02 m/s / 398 fpm (Standard plus)",
        "Throw distance": "12 mm (Standard); 20 mm (Standard plus). 35 mm and 45 mm for carton coding",
        "Service interval": "Up to 18 months (13,000 hours) on dye-based inks"
      }
    },
    "6420": {
      "page": "Corvus 6420 datasheet — https://www.corvus.example/wp-content/uploads/2023/06/corvus-6420-datasheet.pdf",
      "specs": {
        "Printhead": "Mk11 Standard (62 µm nozzle) or Mk11 Standard plus (75 µm)",
        "Lines of print": "Up to 6",
        "Character height": "1.8 to 20 mm (Standard); 2.1 to 20 mm (Standard plus)",
        "Max speed, single line": "6.25 m/s / 1,230 fpm (Standard); 7.28 m/s / 1,433 fpm (Standard plus)",
        "Max speed, two line": "2.46 m/s / 484 fpm (Standard); 2.38 m/s / 469 fpm (Standard plus)",
        "Throw distance": "12 mm (Standard); 20 mm (Standard plus). 35 mm and 45 mm for carton coding",
        "Service interval": "Up to 24 months (18,000 hours) on dye-based inks"
      }
    },
    "6440": {
      "page": "Corvus 6440 datasheet MP42172/05 — https://www.corvus.example/wp-content/uploads/2023/06/corvus-6440-datasheet-mp42172_05.pdf",
      "specs": {
        "Printhead": "Mk11 Standard (62 µm nozzle) or Mk11 Standard plus (75 µm)",
        "Lines of print": "Up to 5",
        "Character height": "1.8 to 20 mm (Standard); 2.1 to 20 mm (Standard plus)",
        "Max speed, single line": "6.25 m/s / 1,230 fpm (Standard); 9.10 m/s / 1,791 fpm (Standard plus)",
        "Max speed, two line": "2.65 m/s / 522 fpm (Standard); 2.56 m/s / 504 fpm (Standard plus)",
        "Throw distance": "12 mm (Standard); 20 mm (Standard plus). 35 mm and 45 mm for carton coding",
        "Ingress protection": "IP65",
        "Service interval": "Up to 24 months (18,000 hours) on dye-based inks"
      }
    },
    "6400PLUS": {
      "page": "Corvus 6400 Plus Series specification sheet — Datasheets/Literature_CIJ_Corvus6400PlusSeries_SpecSheetWEB.md",
      "specs": {
        "Printhead": "MK 11 Standard Plus, 2M conduit standard (4M and 6M options)",
        "Max lines of print": "3",
        "Character height": "0.083\" to 0.421\"",
        "Max speed, single line": "557 fpm",
        "Ink range": "Soft pigmented based, single range",
        "Ingress protection": "IP55",
        "Operating temperature": "41 to 113 °F",
        "Service interval": "Up to 12 months (6,000 hours)"
      }
    },
    "6410PLUS": {
      "page": "Corvus 6400 Plus Series specification sheet — Datasheets/Literature_CIJ_Corvus6400PlusSeries_SpecSheetWEB.md",
      "specs": {
        "Printhead": "MK 11 Standard Plus, 2M conduit standard (4M and 6M options)",
        "Max lines of print": "5",
        "Character height": "0.083\" to 0.531\"",
        "Carton coding height": "0.791\"",
        "Max speed, single line": "1,433 fpm",
        "Ink range": "Soft pigmented based, multiple ranges",
        "Ingress protection": "IP55",
        "Operating temperature": "41 to 113 °F",
        "Service interval": "Up to 12 months (6,000 hours)"
      }
    },
    "6420PLUS": {
      "page": "Corvus 6400 Plus Series specification sheet — Datasheets/Literature_CIJ_Corvus6400PlusSeries_SpecSheetWEB.md",
      "specs": {
        "Printhead": "MK 11 Standard Plus, 2M conduit standard (4M and 6M options)",
        "Max lines of print": "5",
        "Character height": "0.083\" to 0.531\"",
        "Carton coding height": "0.791\"",
        "Max speed, single line": "1,433 fpm",
        "Ink range": "Soft pigmented based, multiple ranges",
        "Ingress protection": "IP65",
        "Operating temperature": "41 to 113 °F",
        "Service interval": "Up to 12 months (6,000 hours)"
      }
    },
    "6440PLUS": {
      "page": "Corvus 6400 Plus Series specification sheet — Datasheets/Literature_CIJ_Corvus6400PlusSeries_SpecSheetWEB.md",
      "specs": {
        "Printhead": "MK 11 Standard Plus, 2M conduit standard (4M and 6M options)",
        "Max lines of print": "5",
        "Character height": "0.083\" to 0.531\"",
        "Carton coding height": "0.791\"",
        "Max speed, single line": "1,791 fpm",
        "Ink range": "Soft pigmented based, multiple ranges",
        "Ingress protection": "IP65",
        "Operating temperature": "41 to 113 °F",
        "Service interval": "Up to 12 months (6,000 hours)"
      }
    },
    "T400 Series": {
      "page": "Thorne T400 Series specification sheet — Datasheets/Literature_TTO_ThorneNGT_SpecSheetWEB.md",
      "specs": {
        "Models": "T402+, T404+, T406e, T408, T408e",
        "Print area, intermittent": "2.1 x 3\" (T402+) up to 8.4 x 6.1\" (T408e)",
        "Print area, continuous": "2.1 x 39\" (T402+) up to 8.4 x 39\" (T408)",
        "Print speed, intermittent": "2 to 23.6 in/sec (T402+); 2 to 9.8 in/sec (T408, T408e)",
        "Print speed, continuous": "3 to 35 m/min (115 ft/min) on T402+; 3 to 14 m/min (46 ft/min) on T408",
        "Print resolution": "12 dots/mm (300 dpi)",
        "Operating environment": "5 to 40 °C, humidity 20 to 75% non-condensing",
        "Ingress protection": "IP20 (power supply IP65)",
        "Air pressure": "1.5 to 5 bar (22 to 72 psi)"
      }
    },
    "K84X": {
      "page": "Kestrel K84X specifications — https://www.kestrel.example/products/printers/print-engines/s84nx/specifications/",
      "specs": {
        "Print method": "Direct thermal transfer, or direct thermal only",
        "Print resolution": "203 dpi, 305 dpi or 609 dpi",
        "Print speed": "16 ips at 203 dpi; 14 ips at 305 dpi; 6 ips at 609 dpi",
        "Print width": "104 mm (4.1\")",
        "Media width": "13 to 131 mm (0.51\" to 5.16\")",
        "Memory": "CPU 1: 2 GB flash, 256 MB RAM. CPU 2: 4 MB flash, 64 MB RAM"
      }
    },
    "K86X": {
      "page": "Kestrel K86X specifications — https://www.kestrel.example/products/printers/print-engines/s86nx/specifications/",
      "specs": {
        "Print method": "Direct thermal transfer, or direct thermal only",
        "Print resolution": "203 dpi or 305 dpi",
        "Print speed": "14 ips at 203 dpi; 12 ips at 305 dpi",
        "Print width": "167.5 mm (6.6\")",
        "Media width": "54 to 180 mm (2.13\" to 7.09\")",
        "Memory": "CPU 1: 2 GB flash, 256 MB RAM. CPU 2: 4 MB flash, 64 MB RAM"
      }
    },
    "Mark 2": {
      "page": "Ridgeline 3200 technical datasheet DRESSP0424 — https://www.axim.example/Portals/0/adam/Content/zCAv1fNCWEqGxnl1RvOluA/DownloadUrl/Ridgeline%205000%20Technical%20Datasheet-1.pdf",
      "specs": {
        "Print height": "2\"",
        "Printhead size": "L 17.6\" x W 2.5\" x H 4.6\", 6 lb",
        "Print resolution": "64 x 300 DPI (100 to 300 DPI user selectable)",
        "Print speed, text": "Up to 250 fpm at 200 DPI; up to 130 fpm at 300 DPI",
        "Print speed, barcode": "Up to 150 fpm at 200 DPI",
        "Throw distance": "Up to 1/4\" for barcodes; up to 1/2\" for text. Best barcodes at 1/8\" and 300 DPI",
        "Print options": "Side panel, incline panel, angled print head",
        "Ingress protection": "IP65 (estimated)",
        "Operating temperature": "40 to 104 °F",
        "Operating humidity": "5 to 90% non-condensing",
        "Technology": "Piezoelectric (Trident impulse jet)",
        "Ink": "ScanMark pigmented black, porous substrates only",
        "Electrical": "24 VDC, 2 A input",
        "Communications": "WiFi IEEE 802.11n, Ethernet IEEE 802.3",
        "Cleaning consumable": "0.6 ml ScanMark ink"
      }
    },
    "Mark 4": {
      "page": "Ridgeline 3200 technical datasheet DRESSP0424 — https://www.axim.example/Portals/0/adam/Content/zCAv1fNCWEqGxnl1RvOluA/DownloadUrl/Ridgeline%205000%20Technical%20Datasheet-1.pdf",
      "specs": {
        "Print height": "4\"",
        "Printhead size": "L 18.7\" x W 2.5\" x H 6.3\", 9.5 lb",
        "Print resolution": "64 x 300 DPI (100 to 300 DPI user selectable)",
        "Print speed, text": "Up to 250 fpm at 200 DPI; up to 130 fpm at 300 DPI",
        "Print speed, barcode": "Up to 150 fpm at 200 DPI",
        "Throw distance": "Up to 1/4\" for barcodes; up to 1/2\" for text. Best barcodes at 1/8\" and 300 DPI",
        "Print options": "Side panel, incline panel, angled print head",
        "Ingress protection": "IP65 (estimated)",
        "Operating temperature": "40 to 104 °F",
        "Operating humidity": "5 to 90% non-condensing",
        "Technology": "Piezoelectric (Trident impulse jet)",
        "Ink": "ScanMark pigmented black, porous substrates only",
        "Electrical": "24 VDC, 2 A input",
        "Communications": "WiFi IEEE 802.11n, Ethernet IEEE 802.3",
        "Cleaning consumable": "0.7 ml ScanMark ink"
      }
    },
    "7300": {
      "page": "Corvus 7300 Series brochure MP41306/2 — https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
      "specs": {
        "Printhead": "PH4 Standard (62 µm) or PH4 Standard Plus (75 µm). The brochure lists no PH4 Compact figures for this model.",
        "Lines of print": "Up to 3",
        "Character height": "1.8 to 8.8 mm (Standard); 2.1 to 10.7 mm (Standard Plus)",
        "Max speed, single line": "2.83 m/s / 557 fpm (Standard); 2.83 m/s / 557 fpm (Standard Plus)",
        "Max speed, two line": "1.41 m/s / 278 fpm (Standard); 1.41 m/s / 278 fpm (Standard Plus)",
        "Throw distance": "12 mm (Standard); 20 mm (Standard Plus). 35 mm and 45 mm for carton coding",
        "Ingress protection": "IP55",
        "Operating temperature": "5 to 45 °C / 41 to 113 °F (0 to 50 °C for Corvus 1240, 1010, 1014 and 3240 inks)",
        "Ink range": "Dye based black and colours; soft pigmented colours",
        "Service interval": "Up to 18 months (13,000 hours) on dye based; up to 12 months (6,000 hours) on soft pigmented",
        "Weight": "23.2 kg including fluids and 2 m printhead"
      }
    },
    "7310": {
      "page": "Corvus 7300 Series brochure MP41306/2 — https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
      "specs": {
        "Printhead": "PH4 Compact (50 µm), PH4 Standard (62 µm) or PH4 Standard Plus (75 µm)",
        "Lines of print": "Up to 3",
        "Character height": "1.2 to 9 mm (Compact); 1.8 to 20 mm (Standard); 2.1 to 20 mm (Standard Plus)",
        "Max speed, single line": "4.39 m/s / 864 fpm (Compact); 6.25 m/s / 1,230 fpm (Standard); 7.28 m/s / 1,433 fpm (Standard Plus)",
        "Max speed, two line": "1.57 m/s / 309 fpm (Compact); 2.09 m/s / 411 fpm (Standard); 2.02 m/s / 398 fpm (Standard Plus)",
        "Throw distance": "4 mm (Compact); 12 mm (Standard); 20 mm (Standard Plus). 35 mm and 45 mm for carton coding",
        "Ingress protection": "IP55",
        "Operating temperature": "5 to 45 °C / 41 to 113 °F (0 to 50 °C for Corvus 1240, 1010, 1014 and 3240 inks)",
        "Ink range": "Dye based black and colours; soft pigmented colours",
        "Service interval": "Up to 18 months (13,000 hours) on dye based; up to 12 months (6,000 hours) on soft pigmented",
        "Weight": "23.2 kg including fluids and 2 m printhead"
      }
    },
    "7320": {
      "page": "Corvus 7300 Series brochure MP41306/2 — https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
      "specs": {
        "Printhead": "PH4 Compact (50 µm), PH4 Standard (62 µm) or PH4 Standard Plus (75 µm)",
        "Lines of print": "Up to 6",
        "Character height": "1.2 to 11.2 mm (Compact); 1.8 to 20 mm (Standard); 2.1 to 20 mm (Standard Plus)",
        "Max speed, single line": "6.28 m/s / 1,236 fpm (Compact); 6.25 m/s / 1,230 fpm (Standard); 7.28 m/s / 1,433 fpm (Standard Plus)",
        "Max speed, two line": "2.19 m/s / 431 fpm (Compact); 2.46 m/s / 484 fpm (Standard); 2.38 m/s / 469 fpm (Standard Plus)",
        "Throw distance": "4 mm (Compact); 12 mm (Standard); 20 mm (Standard Plus). 35 mm and 45 mm for carton coding",
        "Ingress protection": "IP55",
        "Operating temperature": "5 to 45 °C / 41 to 113 °F (0 to 50 °C for Corvus 1240, 1010, 1014 and 3240 inks)",
        "Ink range": "Dye based black and colours; soft pigmented colours",
        "Service interval": "Up to 24 months (17,400 hours) on dye based; up to 12 months (6,000 hours) on soft pigmented",
        "Weight": "23.2 kg including fluids and 2 m printhead"
      }
    },
    "7340": {
      "page": "Corvus 7300 Series brochure MP41306/2 — https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
      "specs": {
        "Printhead": "PH4 Compact (50 µm), PH4 Standard (62 µm) or PH4 Standard Plus (75 µm)",
        "Lines of print": "Up to 6",
        "Character height": "1.2 to 11.2 mm (Compact); 1.8 to 20 mm (Standard); 2.1 to 20 mm (Standard Plus)",
        "Max speed, single line": "6.28 m/s / 1,236 fpm (Compact); 7.50 m/s / 1,476 fpm (Standard); 9.10 m/s / 1,791 fpm (Standard Plus); 10.00 m/s / 1,969 fpm (Standard Plus tower print, 5 dot high)",
        "Max speed, two line": "2.44 m/s / 480 fpm (Compact); 2.65 m/s / 522 fpm (Standard); 2.56 m/s / 504 fpm (Standard Plus)",
        "Throw distance": "4 mm (Compact); 12 mm (Standard); 20 mm (Standard Plus). 35 mm and 45 mm for carton coding, 5 mm for high speed cabling",
        "Ingress protection": "IP65",
        "Operating temperature": "5 to 45 °C / 41 to 113 °F (0 to 50 °C for Corvus 1240, 1010, 1014 and 3240 inks)",
        "Ink range": "Dye based black and colours; soft pigmented colours",
        "Service interval": "Up to 24 months (17,400 hours) on dye based; up to 12 months (6,000 hours) on soft pigmented",
        "Weight": "23.2 kg including fluids and 2 m printhead"
      }
    },
    "7340 Prism": {
      "page": "Corvus 7300 Series brochure MP41306/2 — https://www.corvus.example/wp-content/uploads/2026/06/Corvus-7300-Brochure-v2.pdf",
      "specs": {
        "Printhead": "PH4 Compact (50 µm), PH4 Standard (62 µm) or PH4 Standard Plus (75 µm). No 6 m conduit option on this model.",
        "Lines of print": "Up to 6",
        "Character height": "1.2 to 9 mm (Compact); 1.8 to 16 mm (Standard); 2.1 to 17 mm (Standard Plus)",
        "Max speed, single line": "6.28 m/s / 1,236 fpm (Compact); 7.50 m/s / 1,476 fpm (Standard); 9.10 m/s / 1,791 fpm (Standard Plus); 10.00 m/s / 1,969 fpm (Standard Plus tower print, 5 dot high)",
        "Max speed, two line": "2.44 m/s / 480 fpm (Compact); 2.65 m/s / 522 fpm (Standard); 2.56 m/s / 504 fpm (Standard Plus)",
        "Throw distance": "4 mm (Compact); 12 mm (Standard); 20 mm (Standard Plus). 35 mm and 45 mm for carton coding, 5 mm for high speed cabling",
        "Ingress protection": "IP65",
        "Operating temperature": "5 to 45 °C / 41 to 113 °F",
        "Ink range": "Hard pigmented white and colours",
        "Service interval": "Up to 12 months (8,000 hours) on hard pigmented",
        "Weight": "25.1 kg including fluids and 2 m printhead"
      }
    }
  };
